export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  badge?: string
  description?: string
}

export const allProducts: Product[] = [
  // Our Collection
  {
    id: 1,
    name: "Premium Barfi Mix",
    category: "collection",
    price: 450,
    image: "/premium-barfi-mix.jpg",
    rating: 4.8,
    reviews: 124,
    badge: "Popular",
  },
  {
    id: 2,
    name: "Kaju Katli",
    category: "collection",
    price: 550,
    originalPrice: 650,
    image: "/kaju-katli.jpg",
    rating: 4.9,
    reviews: 98,
    badge: "Top Rated",
  },
  {
    id: 3,
    name: "Gulab Jamun",
    category: "collection",
    price: 380,
    originalPrice: 480,
    image: "/gulab-jamun.png",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 4,
    name: "Rasgulla",
    category: "collection",
    price: 320,
    originalPrice: 420,
    image: "/rasgulla.png",
    rating: 4.6,
    reviews: 89,
  },

  // Best Sellers
  {
    id: 5,
    name: "Gulab Jamun Deluxe",
    category: "bestsellers",
    price: 450,
    originalPrice: 550,
    image: "/best-seller-1.jpg",
    rating: 4.8,
    reviews: 324,
    badge: "Best Seller",
  },
  {
    id: 6,
    name: "Kaju Katli Premium",
    category: "bestsellers",
    price: 650,
    originalPrice: 800,
    image: "/best-seller-2.jpg",
    rating: 4.9,
    reviews: 512,
    badge: "Top Rated",
  },
  {
    id: 7,
    name: "Rasgulla Assorted",
    category: "bestsellers",
    price: 380,
    originalPrice: 480,
    image: "/best-seller-3.jpg",
    rating: 4.7,
    reviews: 289,
    badge: "Best Seller",
  },
  {
    id: 8,
    name: "Barfi Collection",
    category: "bestsellers",
    price: 520,
    originalPrice: 650,
    image: "/best-seller-4.jpg",
    rating: 4.8,
    reviews: 401,
    badge: "Popular",
  },

  // Snacks And Savories
  {
    id: 9,
    name: "Chikhalwali Namkeen",
    category: "snacks",
    price: 180,
    image: "/snacks-1.jpg",
    rating: 4.6,
    reviews: 78,
    description: "Crispy and savory",
  },
  {
    id: 10,
    name: "Chakli Mix",
    category: "snacks",
    price: 220,
    image: "/snacks-2.jpg",
    rating: 4.7,
    reviews: 95,
    description: "Traditional spiral snack",
  },
  {
    id: 11,
    name: "Mathri Assorted",
    category: "snacks",
    price: 150,
    image: "/snacks-3.jpg",
    rating: 4.5,
    reviews: 67,
    description: "Crunchy and delicious",
  },
  {
    id: 12,
    name: "Chivda Special",
    category: "snacks",
    price: 200,
    image: "/snacks-4.jpg",
    rating: 4.6,
    reviews: 89,
    description: "Mixed savory delight",
  },
  {
    id: 13,
    name: "Sev Bhujia",
    category: "snacks",
    price: 160,
    image: "/snacks-5.jpg",
    rating: 4.7,
    reviews: 112,
    description: "Golden and crispy",
  },
  {
    id: 14,
    name: "Fafda Pack",
    category: "snacks",
    price: 190,
    image: "/snacks-6.jpg",
    rating: 4.8,
    reviews: 134,
    description: "Authentic Gujarati snack",
  },

  // In House Bakes
  {
    id: 15,
    name: "Chocolate Cake",
    category: "bakes",
    price: 600,
    image: "/decadent-chocolate-cake.png",
    rating: 4.8,
    reviews: 134,
  },
  {
    id: 16,
    name: "Vanilla Cake",
    category: "bakes",
    price: 550,
    image: "/vanilla-cake.png",
    rating: 4.7,
    reviews: 102,
  },
  {
    id: 17,
    name: "Carrot Cake",
    category: "bakes",
    price: 580,
    image: "/delicious-carrot-cake.png",
    rating: 4.6,
    reviews: 76,
  },
  {
    id: 18,
    name: "Eggless Cake",
    category: "bakes",
    price: 620,
    image: "/eggless-cake.png",
    rating: 4.9,
    reviews: 145,
  },

  // Cakes
  {
    id: 19,
    name: "Black Forest Cake",
    category: "cakes",
    price: 800,
    image: "/black-forest-cake.png",
    rating: 4.9,
    reviews: 178,
  },
  {
    id: 20,
    name: "Cheesecake",
    category: "cakes",
    price: 750,
    image: "/classic-cheesecake.png",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 21,
    name: "Red Velvet Cake",
    category: "cakes",
    price: 700,
    image: "/red-velvet-cake.jpg",
    rating: 4.7,
    reviews: 123,
  },
  {
    id: 22,
    name: "Strawberry Cake",
    category: "cakes",
    price: 680,
    image: "/strawberry-cake.png",
    rating: 4.8,
    reviews: 134,
  },

  // Sweets
  {
    id: 23,
    name: "Halwa",
    category: "sweets",
    price: 320,
    image: "/halwa.jpg",
    rating: 4.7,
    reviews: 98,
  },
  {
    id: 24,
    name: "Khir",
    category: "sweets",
    price: 280,
    image: "/khir.jpg",
    rating: 4.6,
    reviews: 76,
  },
  {
    id: 25,
    name: "Payesh",
    category: "sweets",
    price: 300,
    image: "/payesh.jpg",
    rating: 4.8,
    reviews: 112,
  },
  {
    id: 26,
    name: "Shrikhand",
    category: "sweets",
    price: 350,
    image: "/shrikhand.jpg",
    rating: 4.7,
    reviews: 89,
  },

  // Namkeen
  {
    id: 27,
    name: "Sev",
    category: "namkeen",
    price: 150,
    image: "/sev.jpg",
    rating: 4.6,
    reviews: 67,
  },
  {
    id: 28,
    name: "Bhujia",
    category: "namkeen",
    price: 180,
    image: "/bhujia.jpg",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 29,
    name: "Fafda",
    category: "namkeen",
    price: 200,
    image: "/fafda.jpg",
    rating: 4.5,
    reviews: 54,
  },
  {
    id: 30,
    name: "Chakli",
    category: "namkeen",
    price: 220,
    image: "/chakli.jpg",
    rating: 4.8,
    reviews: 101,
  },
]
