export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  badge?: string
  description?: string
}

export const allProducts: Product[] = [
  // Our Collection
  {
    id: 1,
    name: "Premium Barfi Mix",
    category: "collection",
    price: 450,
    image: "https://www.shreemithai.com/cdn/shop/files/royal-burfi-573357.jpg?v=1723849417",
    rating: 4.8,
    reviews: 124,
    badge: "Popular",
  },
  {
    id: 2,
    name: "Kaju Katli",
    category: "collection",
    price: 500,
    originalPrice: 650,
    image: "https://static.toiimg.com/photo/55048826.cms",
    rating: 4.9,
    reviews: 98,
    badge: "Top Rated",
  },
  {
    id: 3,
    name: "Gulab Jamun",
    category: "collection",
    price: 250,
    originalPrice: 280,
    image: "https://sharmanjainsweets.com/cdn/shop/articles/Untitled_design_eb07557c-e535-4bdf-9063-8a1f1cffa58c.png?v=1751535882",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 4,
    name: "Rasgulla",
    category: "collection",
    price: 320,
    originalPrice: 400,
    image: "https://img.freepik.com/premium-photo/photography-tasty-indian-rasgulla-plate_1288657-51220.jpg",
    rating: 4.6,
    reviews: 89,
  },

  // Best Sellers
  {
  id: 5,
    name: "Gulab Jamun",
    category: "bestsellers",
    price: 250,
    originalPrice: 280,
    image: "https://sharmanjainsweets.com/cdn/shop/articles/Untitled_design_eb07557c-e535-4bdf-9063-8a1f1cffa58c.png?v=1751535882",
    rating: 4.7,
    reviews: 156,
    badge: "Best Seller",
  },
  // {
  //   id: 6,
  //  name: "Kaju Katli",
  //   category: "bestsellers",
  //   price: 500,
  //   originalPrice: 650,
  //   image: "https://static.toiimg.com/photo/55048826.cms",
  //   rating: 4.9,
  //   reviews: 98,
  //   badge: "Top Rated",
  // },
  // {
  //   id: 7,
  //   name: "Rasgulla",
  //   category: "bestsellers",
  //   price: 320,
  //   originalPrice: 400,
  //   image: "https://img.freepik.com/premium-photo/photography-tasty-indian-rasgulla-plate_1288657-51220.jpg",
  //   rating: 4.6,
  //   reviews: 89,
  //   badge: "Best Seller",
  // },
  // {
  //   id: 8,
  //   name: "Premium Barfi Mix",
  //   category: "bestsellers",
  //   price: 450,
  //   image: "https://www.shreemithai.com/cdn/shop/files/royal-burfi-573357.jpg?v=1723849417",
  //   rating: 4.8,
  //   reviews: 124,
  //   badge: "Popular",
  // },

  // Snacks And Savories
  {
    id: 9,
    name: "BhakarWadi",
    category: "snacks",
    price: 180,
    image: "https://morbiwalasweets.com/cdn/shop/files/37_e57a0058-901e-415f-aedd-33ba5b18357b.png?v=1690328231",
    rating: 4.6,
    reviews: 78,
    description: "Crispy and savory",
  },
  {
    id: 10,
    name: "Chakli",
    category: "snacks",
    price: 220,
    image: "https://patilkaki.com/cdn/shop/files/ChakliSI-1500x1500.jpg?v=1741166632",
    rating: 4.7,
    reviews: 95,
    description: "Traditional spiral snack",
  },
  {
    id: 11,
    name: "Kachori",
    category: "snacks",
    price: 150,
    image: "https://www.jcookingodyssey.com/wp-content/uploads/2022/03/Dry-fruit-masala-kachori-4.jpg",
    rating: 4.5,
    reviews: 67,
    description: "Crunchy and delicious",
  },
  {
    id: 12,
    name: "Maka Chivda Special",
    category: "namkeen",
    price: 200,
    image: "https://day2dayfoods.com/wp-content/uploads/2021/12/maka-chivda1.jpg",
    rating: 4.6,
    reviews: 89,
    description: "Mixed savory delight",
  },
  {
    id: 13,
    name: "Sev Bhujia",
    category: "snacks",
    price: 160,
    image: "https://img.freepik.com/premium-photo/aloo-bhujiya-potato-bhujia-also-known-as-namkeen-sev-popular-bikaneri-recipe-served-bowl-plate-selective-focus_466689-41997.jpg",
    rating: 4.7,
    reviews: 112,
    description: "Golden and crispy",
  },
  {
    id: 14,
    name: "Fafda Pack",
    category: "snacks",
    price: 190,
    image: "https://t4.ftcdn.net/jpg/07/06/94/35/360_F_706943528_STfJxesEs1Ldku7f1jOrd24f0DVSdXGb.jpg",
    rating: 4.8,
    reviews: 134,
    description: "Authentic Gujarati snack",
  },

  // In House Bakes
  {
    id: 15,
    name: "Chocolate Cake",
    category: "bakes",
    price: 600,
    image: "https://www.warmoven.in/cdn/shop/files/premium_midnight_ganache_cake.jpg?v=1749833733",
    rating: 4.8,
    reviews: 134,
  },
  {
    id: 16,
    name: "Vanilla Cake",
    category: "bakes",
    price: 550,
    image: "https://imgcdn.floweraura.com/eggless-anniversary-vanilla-cake-9913230ca-AA.jpg",
    rating: 4.7,
    reviews: 102,
  },
  {
    id: 17,
    name: "PineApple Cake",
    category: "bakes",
    price: 580,
    image: "https://liliyum.com/cdn/shop/products/Pineapple-Mousse-Cake-1_2400x.jpg?v=1630928051",
    rating: 4.6,
    reviews: 76,
  },
  {
    id: 18,
    name: "Rasmalai Cake",
    category: "bakes",
    price: 620,
    image: "https://imgcdn.floweraura.com/rasmalai-pista-delight-cake-9744420ca-A.jpg",
    rating: 4.9,
    reviews: 145,
  },

  // Cakes
  {
    id: 19,
    name: "Black Forest Cake",
    category: "cakes",
    price: 800,
    image: "https://theambrosia.com/wp-content/uploads/2024/12/Black-Forest-scaled-e1639810324908.jpg",
    rating: 4.9,
    reviews: 178,
  },
  {
    id: 20,
    name: "Cheesecake",
    category: "cakes",
    price: 750,
    image: "https://yummycake.in/wp-content/uploads/2015/03/Lemon-Cheesecake.png",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: 21,
    name: "Red Velvet Cake",
    category: "cakes",
    price: 700,
    image: "/red-velvet-cake.jpg",
    rating: 4.7,
    reviews: 123,
  },
  {
    id: 22,
    name: "Strawberry Cake",
    category: "cakes",
    price: 680,
    image: "/strawberry-cake.png",
    rating: 4.8,
    reviews: 134,
  },

  // Sweets
  {
    id: 23,
    name: "Halwa",
    category: "sweets",
    price: 320,
    image: "/halwa.jpg",
    rating: 4.7,
    reviews: 98,
  },
  {
    id: 24,
    name: "Khir",
    category: "sweets",
    price: 280,
    image: "/khir.jpg",
    rating: 4.6,
    reviews: 76,
  },
  {
    id: 25,
    name: "BaluShahi",
    category: "sweets",
    price: 300,
    image: "https://www.govindam.co.in/wp-content/uploads/2025/01/Balushahi-3.webp",
    rating: 4.8,
    reviews: 112,
  },
  {
    id: 26,
    name: "Shrikhand",
    category: "sweets",
    price: 350,
    image: "https://img.freepik.com/premium-photo/shrikhand-srikhand-is-indian-dessert-made-strained-yogurt-garnished-with-dry-fruits-saffron_466689-25381.jpg",
    rating: 4.7,
    reviews: 89,
  },

  // Namkeen
  {
    id: 27,
    name: "Potato Wafers",
    category: "namkeen",
    price: 150,
    image: "https://tiimg.tistatic.com/fp/1/007/548/salty-potato-chips-fried-fat-36-58g-protein-6-75g-gluten-free--423.jpg",
    rating: 4.6,
    reviews: 67,
  },
  {
    id: 28,
    name: "Farsan",
    category: "namkeen",
    price: 180,
    image: "https://tiimg.tistatic.com/fp/1/007/985/1-kg-packed-crispy-salty-and-spicy-farsan-namkeen-807.jpg",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 29,
    name: "Moong Dal",
    category: "namkeen",
    price: 200,
    image: "https://heerson.com/cdn/shop/files/Heerson_Salted_Moong_Dal._Moong_dal_and_iodised_salt_blend..jpg?v=1759778898&width=1200",
    rating: 4.5,
    reviews: 54,
  },
  {
    id: 30,
    name: "Poha Chivda",
    category: "namkeen",
    price: 220,
    image: "https://www.vaidehifoods.com/wp-content/uploads/2019/12/bhajke-poha-chiwda1-1.jpg",
    rating: 4.8,
    reviews: 101,
  },
]
